spring:
    datasource:
        url: jdbc:mysql://localhost:3306/downloader
        username: root
        password: root
        platform: mysql
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: false

endpoints:
  prometheus:
    enabled: true

management:
     endpoint:
          metrics:
             enabled: true

logging:
    level:
        org.springframework.web: DEBUG
        com.zaxxer: false
        root: DEBUG
